name: flutter_custom_bottom_navigation_bar
description: Flutter Custom Bottom Navigation Bar Example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  flutter_staggered_grid_view: "^0.3.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/img_01.jpg
    - assets/images/img_02.jpg
    - assets/images/img_03.jpg
    - assets/images/img_04.jpg
    - assets/images/img_05.jpg
    - assets/images/img_06.jpg
    - assets/images/img_07.jpg
    - assets/images/img_08.jpg
    - assets/images/img_09.jpg
    - assets/images/img_10.jpg
    - assets/images/img_11.jpg
    - assets/images/img_12.jpg
    - assets/images/img_13.jpg
    - assets/images/img_14.jpg
    - assets/images/img_15.jpg
    - assets/images/img_16.jpg
    - assets/images/img_17.jpg
    - assets/images/img_18.jpg
    - assets/images/img_19.jpg
    - assets/images/img_20.jpg
